/*********************************************************************************
* This file is part of OntoQL Project.
* Copyright (C) 2006  LISI - ENSMA
*   Teleport 2 - 1 avenue Clement Ader
*   BP 40109 - 86961 Futuroscope Chasseneuil Cedex - FRANCE
* 
* OntoQL is free software: you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.
*
* OntoQL is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU Lesser General Public License for more details.
* 
* You should have received a copy of the GNU Lesser General Public License
* along with OntoQL.  If not, see <http://www.gnu.org/licenses/>.
**********************************************************************************/
package fr.ensma.lisi.ontoql.engine;

import java.io.InputStream;
import java.io.Reader;

import org.hibernate.QueryException;

import fr.ensma.lisi.ontoql.engine.antlr.SPARQLBaseLexer;

/**
 * Custom lexer for the SPARQL grammar. Extends the base lexer generated by
 * ANTLR in order to keep the grammar source file clean.
 * 
 * @author Stéphane JEAN
 */
class SPARQLLexer extends SPARQLBaseLexer {

	/**
	 * Constructor with an InputStream.
	 * 
	 * @param in an input InputStream
	 */
	public SPARQLLexer(final InputStream in) {
		super(in);
	}

	/**
	 * Constructor with a Reader.
	 * 
	 * @param in input Reader
	 */
	public SPARQLLexer(final Reader in) {
		super(in);
	}

	@Override
	public void panic() {
		panic("CharScanner: panic");
	}

	@Override
	public void panic(final String s) {
		// overriden to avoid System.exit
		throw new QueryException(s);
	}
}
